# Generated by Django 4.2.7 on 2024-03-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0002_remove_categoria_pai_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
