# Generated by Django 4.2.7 on 2024-03-24 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('suprimentos', '0003_categoria_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_alteracao', models.DateTimeField(default=None, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_categoria', to='suprimentos.categoria')),
                ('usuario_cadastro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_criado', to=settings.AUTH_USER_MODEL)),
                ('usuario_ultima_alteracao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item_editado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
