# Generated by Django 4.2.7 on 2023-11-21 01:10

import colaborador.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=14, unique=True, validators=[colaborador.validators.validar_cpf])),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
    ]
