# Generated by Django 4.2.7 on 2023-11-22 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colaborador', '0001_initial'),
        ('empresa', '0001_initial'),
        ('tipo_equipamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_patrimonio', models.CharField(max_length=30, unique=True)),
                ('pedido', models.CharField(blank=True, max_length=20, null=True)),
                ('data_compra', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('0', 'Novo'), ('1', 'Em operação'), ('2', 'Em manutenção'), ('3', 'Disponivel'), ('4', 'Indisponível')], max_length=1)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('especificacoes', models.CharField(blank=True, max_length=100, null=True)),
                ('acesso_remoto', models.CharField(blank=True, max_length=50, null=True)),
                ('acesso_id', models.CharField(blank=True, max_length=50, null=True)),
                ('acesso_senha', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ultima_alteracao', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('colaborador', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, to='colaborador.colaborador')),
                ('empresa', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, to='empresa.empresa')),
                ('tipo_equipamento', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, to='tipo_equipamento.tipoequipamento')),
            ],
        ),
    ]
