# Generated by Django 4.2.7 on 2024-02-04 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipo_equipamento', '__first__'),
        ('empresa', '__first__'),
        ('colaborador', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_patrimonio', models.CharField(max_length=30, unique=True)),
                ('pedido', models.CharField(blank=True, max_length=20, null=True)),
                ('data_compra', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('0', 'Novo'), ('1', 'Em operação'), ('2', 'Em manutenção'), ('3', 'Disponivel'), ('4', 'Indisponível')], max_length=1)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('especificacoes', models.CharField(blank=True, max_length=100, null=True)),
                ('acesso_remoto', models.CharField(blank=True, max_length=50, null=True)),
                ('acesso_id', models.CharField(blank=True, max_length=50, null=True)),
                ('acesso_senha', models.CharField(blank=True, max_length=50, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_ultima_alteracao', models.DateTimeField(default=None, null=True)),
                ('status', models.BooleanField(default=True)),
                ('colaborador', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, to='colaborador.colaborador')),
                ('empresa', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, to='empresa.empresa')),
                ('tipo_equipamento', models.ForeignKey(limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, to='tipo_equipamento.tipoequipamento')),
                ('usuario_cadastro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_criados', to=settings.AUTH_USER_MODEL)),
                ('usuario_ultima_alteracao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamento_alterados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('empresa_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_destino', to='empresa.empresa')),
                ('empresa_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferencias_origem', to='empresa.empresa')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamento.equipamento')),
                ('usuario_transferencia_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_transferencia_empresa', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransferenciaColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('colaborador_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador_destino', to='colaborador.colaborador')),
                ('colaborador_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador_origem', to='colaborador.colaborador')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamento.equipamento')),
                ('usuario_transferencia_colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_tranferencia_colaborador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlteracaiSituacaoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_anterior', models.CharField(choices=[('0', 'Novo'), ('1', 'Em operação'), ('2', 'Em manutenção'), ('3', 'Disponivel'), ('4', 'Indisponível')], max_length=1)),
                ('situacao_nova', models.CharField(choices=[('0', 'Novo'), ('1', 'Em operação'), ('2', 'Em manutenção'), ('3', 'Disponivel'), ('4', 'Indisponível')], max_length=1)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamento.equipamento')),
                ('usuario_situacao_equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_situacao_equipamento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
