# Generated by Django 4.2.7 on 2024-02-21 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setor', '0001_initial'),
        ('colaborador', '0003_alter_colaborador_options'),
        ('equipamento', '0002_alter_equipamento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='setor',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='setor.setor'),
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='colaborador',
            field=models.ForeignKey(blank=True, limit_choices_to={'status': True}, null=True, on_delete=django.db.models.deletion.PROTECT, to='colaborador.colaborador'),
        ),
    ]
