# Generated by Django 4.2.7 on 2023-11-23 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0001_initial'),
        ('equipamento', '0002_transferenciaempresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferenciaColaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_transferencia', models.DateTimeField(auto_now_add=True)),
                ('colaborador_destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador_destino', to='colaborador.colaborador')),
                ('colaborador_origem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaborador_origem', to='colaborador.colaborador')),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamento.equipamento')),
            ],
        ),
    ]
