# Generated by Django 4.2.7 on 2024-02-26 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colaborador', '0003_alter_colaborador_options'),
        ('equipamento', '0003_equipamento_setor_alter_equipamento_colaborador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='colaborador',
            field=models.ForeignKey(default=1, limit_choices_to={'status': True}, on_delete=django.db.models.deletion.PROTECT, to='colaborador.colaborador'),
            preserve_default=False,
        ),
    ]
