# Generated by Django 4.2.7 on 2023-12-03 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0003_transferenciacolaborador'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlteracaiSituacaoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacao_anterior', models.CharField(choices=[('0', 'Novo'), ('1', 'Em operação'), ('2', 'Em manutenção'), ('3', 'Disponivel'), ('4', 'Indisponível')], max_length=1)),
                ('situacao_nova', models.CharField(choices=[('0', 'Novo'), ('1', 'Em operação'), ('2', 'Em manutenção'), ('3', 'Disponivel'), ('4', 'Indisponível')], max_length=1)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipamento.equipamento')),
            ],
        ),
    ]
