# Generated by Django 4.2.7 on 2024-01-11 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipamento', '0004_alteracaisituacaoequipamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='alteracaisituacaoequipamento',
            name='usuario_situacao_equipamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_situacao_equipamento', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipamento',
            name='usuario_cadastro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='equipamento',
            name='usuario_ultima_alteracao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamento_alterados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transferenciacolaborador',
            name='usuario_transferencia_colaborador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_tranferencia_colaborador', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transferenciaempresa',
            name='usuario_transferencia_empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='usuario_transferencia_empresa', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
