# Generated by Django 4.2.7 on 2024-01-11 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0005_alteracaisituacaoequipamento_usuario_situacao_equipamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipamento',
            old_name='ultima_alteracao',
            new_name='data_ultima_alteracao',
        ),
    ]
