# Generated by Django 4.2.7 on 2024-01-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipamento', '0006_rename_ultima_alteracao_equipamento_data_ultima_alteracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento',
            name='data_ultima_alteracao',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
