# Generated by Django 4.2.7 on 2023-11-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEquipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['tipo'],
            },
        ),
    ]
