# Generated by Django 4.2.7 on 2024-01-09 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tipo_equipamento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoequipamento',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tipoequipamento',
            name='ultima_alteracao',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tipoequipamento',
            name='usuario_cadastro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_equipamentos_criados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tipoequipamento',
            name='usuario_ultima_alteracao',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipo_equipamento_alterados', to=settings.AUTH_USER_MODEL),
        ),
    ]
