# Generated by Django 4.2.7 on 2024-01-10 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tipo_equipamento', '0002_tipoequipamento_data_cadastro_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tipoequipamento',
            old_name='ultima_alteracao',
            new_name='data_ultima_alteracao',
        ),
    ]
